services:
  jupyter_lab_titanic_gpu:
    build: .
    container_name: titanic_kaggle_gpu_container
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]